# Generated by Django 4.2.20 on 2025-03-26 02:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [    # 1번 설게도에 의존하고 있음
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='uodated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
