# Generated by Django 4.2.20 on 2025-04-01 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_created_at_article_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
            # UPLOAD_TO 는 media/이후의 경로 설정
        ),
    ]
